#!/usr/bin/env python3
"""Fix common JSON syntax errors generated by Claude.

Handles:
0. Trailing commas before closing brackets ({"a": 1,} -> {"a": 1})
1. Unescaped backslashes (Spatie\\Permission -> Spatie\\\\Permission)
2. Missing commas between array elements ("a" "b" -> "a", "b")
3. Missing commas between object properties

Usage: python3 fix-json.py <input_file> <output_file>
"""

import re
import sys
import json


def fix_json(content: str) -> str:
    """Fix common JSON syntax errors."""

    # Pass 0: Remove trailing commas before closing brackets/braces
    # Handles: {"a": 1,} -> {"a": 1} and [1, 2,] -> [1, 2]
    content = re.sub(r',\s*([}\]])', r'\1', content)

    # Pass 1: Fix unescaped backslashes
    # Match backslash NOT preceded by backslash, NOT followed by valid escape char
    content = re.sub(r'(?<!\\)\\(?![\\"/bfnrtu])', r'\\\\', content)

    # Pass 2: Fix missing commas between string values in arrays
    # Pattern: "string1" followed by whitespace/newline then "string2" (missing comma)
    # This handles: "value1"\n        "value2" -> "value1",\n        "value2"
    content = re.sub(
        r'("(?:[^"\\]|\\.)*")\s*\n(\s*)("(?:[^"\\]|\\.)*")',
        r'\1,\n\2\3',
        content
    )

    # Pass 3: Fix missing commas between numbers and strings, strings and numbers
    # "string" 123 -> "string", 123
    content = re.sub(
        r'("(?:[^"\\]|\\.)*")\s*\n(\s*)(\d)',
        r'\1,\n\2\3',
        content
    )
    content = re.sub(
        r'(\d)\s*\n(\s*)("(?:[^"\\]|\\.)*")',
        r'\1,\n\2\3',
        content
    )

    # Pass 4: Fix missing commas between closing brackets and strings/numbers
    # }  "key" -> }, "key"
    # ]  "value" -> ], "value"
    content = re.sub(
        r'(\}|\])\s*\n(\s*)("(?:[^"\\]|\\.)*")',
        r'\1,\n\2\3',
        content
    )

    # Pass 5: Fix missing commas between values and opening brackets
    # "value"  { -> "value", {
    # "value"  [ -> "value", [
    content = re.sub(
        r'("(?:[^"\\]|\\.)*")\s*\n(\s*)(\{|\[)',
        r'\1,\n\2\3',
        content
    )

    # Pass 6: Fix missing commas between closing and opening brackets
    # }  { -> }, {
    # ]  [ -> ], [
    # ]  { -> ], {
    # }  [ -> }, [
    content = re.sub(
        r'(\}|\])\s*\n(\s*)(\{|\[)',
        r'\1,\n\2\3',
        content
    )

    # Pass 7: Fix missing commas between booleans/null and other values
    content = re.sub(
        r'(true|false|null)\s*\n(\s*)(")',
        r'\1,\n\2\3',
        content
    )
    content = re.sub(
        r'("(?:[^"\\]|\\.)*")\s*\n(\s*)(true|false|null)',
        r'\1,\n\2\3',
        content
    )

    return content


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_file> <output_file>", file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Try multiple passes - sometimes one fix reveals another issue
        fixed = content
        for attempt in range(3):
            fixed = fix_json(fixed)
            try:
                json.loads(fixed)
                break  # Valid JSON, we're done
            except json.JSONDecodeError:
                continue  # Try another pass

        # Final validation
        try:
            json.loads(fixed)
        except json.JSONDecodeError as e:
            print(f"Repair failed after 3 attempts - JSON still invalid: {e}", file=sys.stderr)
            sys.exit(2)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(fixed)

        sys.exit(0)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
